version: "3.1"
services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    networks:
      - verdaccio-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./conf:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
      - "./logs:/verdaccio/logs"
    restart: always
volumes:
  verdaccio:
    driver: local
networks:
  verdaccio-network:
    driver: bridge
